name: Playwright Tests

on:
  push:
    branches: [ "**" ]  # Run on all branches

jobs:
  test:
    name: Run Playwright Tests in Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests in Docker (using 'playwright-tests' image)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/tests \
            -w /tests \
            playwright-tests mvn verify

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure/reports

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: extent

      - name: Upload JUnit XML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: target/surefire-reports

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: allure/reports