name: Java Playwright CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-playwright-java .

      - name: Run tests inside Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}/allure-results:/app/target/allure-results \
            my-playwright-java mvn clean test

      - name: Generate Allure report
        run: docker run --rm -v ${{ github.workspace }}/allure-results:/app/target/allure-results -v ${{ github.workspace }}/allure-report:/app/target/allure-report my-playwright-java mvn allure:report

      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results

      - name: Upload Allure report (HTML)
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
