name: Java Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Playwright Java Tests with Allure
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      HEADLESS: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Maven
        uses: s4u/maven-settings-action@v2.8.0

      - name: Install Node.js (for Playwright CLI)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Maven Tests (TestNG + Playwright)
        run: mvn clean test -DsuiteXmlFile=src/test/resources/suites/smokeTests.xml -Dheadless=${HEADLESS}

      - name: Generate Allure Report
        run: |
          echo "Generating Allure report..."
          mkdir -p allure/reports
          mvn allure:report
          ls -la allure/reports || echo "No reports found"

      - name: Upload Allure HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure/reports
          retention-days: 30
