name: Playwright Java Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Playwright Java Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      HEADLESS: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Maven
        uses: s4u/maven-settings-action@v2.8.0

      - name: Set up Node.js (for Playwright CLI)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Maven Tests (TestNG + Playwright)
        run: mvn clean test -DsuiteXmlFile=src/test/resources/suites/smokeTests.xml -Dheadless=${HEADLESS}

      - name: Generate Allure Report
        run: |
          echo "Generating Allure report..."
          mkdir -p allure/reports
          mvn allure:report
          ls -la allure/reports || echo "⚠️ No Allure report generated."

      - name: Upload Allure HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure/reports
          retention-days: 30

      - name: Upload TestNG Results (Surefire)
        uses: actions/upload-artifact@v4
        with:
          name: testng-results
          path: target/surefire-reports
          retention-days: 30
